dist: xenial
language: python
python:
    - "3.7"

install:
      - sudo pip install -U -r requirements.txt

script:
      - travis-sphinx build -s . --nowarn

after_success:
      - travis-sphinx deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master